In [1502]:
import pandas as pd

# Étude du fichier EdStatsCountry-Series.csv

## Partie 1 : Analyse générale des données

### Fichier 1

In [1503]:
df = pd.read_csv('EdStatsCountry-Series.csv')

In [1504]:
df.head(5)

CountryCode         SeriesCode  \
0         ABW        SP.POP.TOTL   
1         ABW        SP.POP.GROW   
2         AFG        SP.POP.GROW   
3         AFG  NY.GDP.PCAP.PP.CD   
4         AFG        SP.POP.TOTL   

                                         DESCRIPTION  Unnamed: 3  
0  Data sources : United Nations World Population...         NaN  
1  Data sources: United Nations World Population ...         NaN  
2  Data sources: United Nations World Population ...         NaN  
3                 Estimates are based on regression.         NaN  
4  Data sources : United Nations World Population...         NaN

In [1505]:
df.shape

(613, 4)

Le fichier contient fichier 613 lignes et 4 colonnes.

In [1506]:
df.isnull().mean()

CountryCode    0.0
SeriesCode     0.0
DESCRIPTION    0.0
Unnamed: 3     1.0
dtype: float64

La colonne 'Unnamed: 3' est vide.
Il ne manque aucune donnée dans les autres colonnes

In [1507]:
country_series = df

### Fichier 2

In [1508]:
df = pd.read_csv('EdStatsCountry.csv')

In [1509]:
df.head(5)

Country Code   Short Name   Table Name                     Long Name  \
0          ABW        Aruba        Aruba                         Aruba   
1          AFG  Afghanistan  Afghanistan  Islamic State of Afghanistan   
2          AGO       Angola       Angola   People's Republic of Angola   
3          ALB      Albania      Albania           Republic of Albania   
4          AND      Andorra      Andorra       Principality of Andorra   

  2-alpha code   Currency Unit  \
0           AW   Aruban florin   
1           AF  Afghan afghani   
2           AO  Angolan kwanza   
3           AL    Albanian lek   
4           AD            Euro   

                                       Special Notes  \
0  SNA data for 2000-2011 are updated from offici...   
1  Fiscal year end: March 20; reporting period fo...   
2  April 2013 database update: Based on IMF data,...   
3                                                NaN   
4                                                NaN   

                      Region          Income Group WB-2 code  ...  \
0  Latin America & Caribbean  High income: nonOECD        AW  ...   
1                 South Asia            Low income        AF  ...   
2         Sub-Saharan Africa   Upper middle income        AO  ...   
3      Europe & Central Asia   Upper middle income        AL  ...   
4      Europe & Central Asia  High income: nonOECD        AD  ...   

            IMF data dissemination standard  \
0                                       NaN   
1  General Data Dissemination System (GDDS)   
2  General Data Dissemination System (GDDS)   
3  General Data Dissemination System (GDDS)   
4                                       NaN   

                            Latest population census  \
0                                               2010   
1                                               1979   
2                                               1970   
3                                               2011   
4  2011. Population figures compiled from adminis...   

                             Latest household survey  \
0                                                NaN   
1  Multiple Indicator Cluster Survey (MICS), 2010/11   
2               Malaria Indicator Survey (MIS), 2011   
3       Demographic and Health Survey (DHS), 2008/09   
4                                                NaN   

   Source of most recent Income and expenditure data  \
0                                                NaN   
1            Integrated household survey (IHS), 2008   
2            Integrated household survey (IHS), 2008   
3  Living Standards Measurement Study Survey (LSM...   
4                                                NaN   

  Vital registration complete Latest agricultural census  \
0                         Yes                        NaN   
1                         NaN                    2013/14   
2                         NaN                       2015   
3                         Yes                       2012   
4                         Yes                        NaN   

  Latest industrial data Latest trade data Latest water withdrawal data  \
0                    NaN            2012.0                          NaN   
1                    NaN            2012.0                         2000   
2                    NaN               NaN                         2005   
3                 2010.0            2012.0                         2006   
4                    NaN            2006.0                          NaN   

  Unnamed: 31  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
4         NaN  

[5 rows x 32 columns]

In [1510]:
df.shape

(241, 32)

Le fichier contient fichier 241 lignes et 32 colonnes.

In [1511]:
mean_null_by_columns_df = df.isnull().mean()
mean_null_by_columns_df

Country Code                                         0.000000
Short Name                                           0.000000
Table Name                                           0.000000
Long Name                                            0.000000
2-alpha code                                         0.012448
Currency Unit                                        0.107884
Special Notes                                        0.398340
Region                                               0.112033
Income Group                                         0.112033
WB-2 code                                            0.004149
National accounts base year                          0.149378
National accounts reference year                     0.867220
SNA price valuation                                  0.182573
Lending category                                     0.402490
Other groups                                         0.759336
System of National Accounts                          0.107884
Alternat

In [1512]:
columns_with_no_null = mean_null_by_columns_df[mean_null_by_columns_df == 0.0]
columns_with_no_null

Country Code    0.0
Short Name      0.0
Table Name      0.0
Long Name       0.0
dtype: float64

Aucune données n'est manquante dans les colonnes ci-dessus

In [1513]:
columns_with_only_null = mean_null_by_columns_df[mean_null_by_columns_df == 1.0]
columns_with_only_null

Unnamed: 31    1.0
dtype: float64

La colonne ci-dessus est vide

In [1514]:
countries = df

### Fichier 3

In [1515]:
df = pd.read_csv('EdStatsData.csv')

In [1516]:
df.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978',
       '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987',
       '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996',
       '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2020', '2025', '2030', '2035', '2040', '2045',
       '2050', '2055', '2060', '2065', '2070', '2075', '2080', '2085', '2090',
       '2095', '2100', 'Unnamed: 69'],
      dtype='object')

In [1517]:
df.head(5)

Country Name Country Code  \
0   Arab World          ARB   
1   Arab World          ARB   
2   Arab World          ARB   
3   Arab World          ARB   
4   Arab World          ARB   

                                      Indicator Name  Indicator Code  \
0  Adjusted net enrolment rate, lower secondary, ...      UIS.NERA.2   
1  Adjusted net enrolment rate, lower secondary, ...    UIS.NERA.2.F   
2  Adjusted net enrolment rate, lower secondary, ...  UIS.NERA.2.GPI   
3  Adjusted net enrolment rate, lower secondary, ...    UIS.NERA.2.M   
4  Adjusted net enrolment rate, primary, both sex...     SE.PRM.TENR   

        1970       1971       1972       1973       1974      1975  ...  2060  \
0        NaN        NaN        NaN        NaN        NaN       NaN  ...   NaN   
1        NaN        NaN        NaN        NaN        NaN       NaN  ...   NaN   
2        NaN        NaN        NaN        NaN        NaN       NaN  ...   NaN   
3        NaN        NaN        NaN        NaN        NaN       NaN  ...   NaN   
4  54.822121  54.894138  56.209438  57.267109  57.991138  59.36554  ...   NaN   

   2065  2070  2075  2080  2085  2090  2095  2100  Unnamed: 69  
0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  
1   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  
2   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  
3   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  
4   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  

[5 rows x 70 columns]

In [1518]:
df.shape

(886930, 70)

Le fichier contient fichier 886 930 lignes et 70 colonnes.

In [1519]:
mean_null_by_columns_df = df.isnull().mean()
mean_null_by_columns_df

Country Name      0.000000
Country Code      0.000000
Indicator Name    0.000000
Indicator Code    0.000000
1970              0.918496
                    ...   
2085              0.942007
2090              0.942007
2095              0.942007
2100              0.942007
Unnamed: 69       1.000000
Length: 70, dtype: float64

In [1520]:
columns_with_no_null = mean_null_by_columns_df[mean_null_by_columns_df == 0.0]
columns_with_no_null

Country Name      0.0
Country Code      0.0
Indicator Name    0.0
Indicator Code    0.0
dtype: float64

Aucune données n'est manquante dans les colonnes ci-dessus

In [1521]:
columns_with_only_null = mean_null_by_columns_df[mean_null_by_columns_df == 1.0]
columns_with_only_null

Unnamed: 69    1.0
dtype: float64

La colonne ci-dessus est vide

In [1522]:
stats = df

### Fichier 4

In [1523]:
df = pd.read_csv('EdStatsFootNote.csv')

In [1524]:
df.head(5)

CountryCode      SeriesCode    Year          DESCRIPTION  Unnamed: 4
0         ABW  SE.PRE.ENRL.FE  YR2001  Country estimation.         NaN
1         ABW  SE.TER.TCHR.FE  YR2005  Country estimation.         NaN
2         ABW  SE.PRE.TCHR.FE  YR2000  Country estimation.         NaN
3         ABW  SE.SEC.ENRL.GC  YR2004  Country estimation.         NaN
4         ABW     SE.PRE.TCHR  YR2006  Country estimation.         NaN

In [1525]:
df.shape

(643638, 5)

Le fichier contient fichier 643638 lignes et 5 colonnes.

In [1526]:
mean_null_by_columns_df = df.isnull().mean()
mean_null_by_columns_df

CountryCode    0.0
SeriesCode     0.0
Year           0.0
DESCRIPTION    0.0
Unnamed: 4     1.0
dtype: float64

In [1527]:
columns_with_no_null = mean_null_by_columns_df[mean_null_by_columns_df == 0.0]
columns_with_no_null

CountryCode    0.0
SeriesCode     0.0
Year           0.0
DESCRIPTION    0.0
dtype: float64

Aucune données n'est manquante dans les colonnes ci-dessus

In [1528]:
columns_with_only_null = mean_null_by_columns_df[mean_null_by_columns_df == 1.0]
columns_with_only_null

Unnamed: 4    1.0
dtype: float64

La colonne ci-dessus est vide

In [1529]:
foot_note = df

### Fichier 5

In [1530]:
df = pd.read_csv('EdStatsSeries.csv')

In [1531]:
df.head(5)

Series Code       Topic  \
0  BAR.NOED.1519.FE.ZS  Attainment   
1     BAR.NOED.1519.ZS  Attainment   
2  BAR.NOED.15UP.FE.ZS  Attainment   
3     BAR.NOED.15UP.ZS  Attainment   
4  BAR.NOED.2024.FE.ZS  Attainment   

                                      Indicator Name  \
0  Barro-Lee: Percentage of female population age...   
1  Barro-Lee: Percentage of population age 15-19 ...   
2  Barro-Lee: Percentage of female population age...   
3  Barro-Lee: Percentage of population age 15+ wi...   
4  Barro-Lee: Percentage of female population age...   

                                    Short definition  \
0  Percentage of female population age 15-19 with...   
1  Percentage of population age 15-19 with no edu...   
2  Percentage of female population age 15+ with n...   
3  Percentage of population age 15+ with no educa...   
4  Percentage of female population age 20-24 with...   

                                     Long definition  Unit of measure  \
0  Percentage of female population age 15-19 with...              NaN   
1  Percentage of population age 15-19 with no edu...              NaN   
2  Percentage of female population age 15+ with n...              NaN   
3  Percentage of population age 15+ with no educa...              NaN   
4  Percentage of female population age 20-24 with...              NaN   

  Periodicity Base Period Other notes Aggregation method  ...  \
0         NaN         NaN         NaN                NaN  ...   
1         NaN         NaN         NaN                NaN  ...   
2         NaN         NaN         NaN                NaN  ...   
3         NaN         NaN         NaN                NaN  ...   
4         NaN         NaN         NaN                NaN  ...   

  Notes from original source  General comments  \
0                        NaN               NaN   
1                        NaN               NaN   
2                        NaN               NaN   
3                        NaN               NaN   
4                        NaN               NaN   

                                              Source  \
0  Robert J. Barro and Jong-Wha Lee: http://www.b...   
1  Robert J. Barro and Jong-Wha Lee: http://www.b...   
2  Robert J. Barro and Jong-Wha Lee: http://www.b...   
3  Robert J. Barro and Jong-Wha Lee: http://www.b...   
4  Robert J. Barro and Jong-Wha Lee: http://www.b...   

  Statistical concept and methodology Development relevance  \
0                                 NaN                   NaN   
1                                 NaN                   NaN   
2                                 NaN                   NaN   
3                                 NaN                   NaN   
4                                 NaN                   NaN   

  Related source links Other web links  Related indicators  License Type  \
0                  NaN             NaN                 NaN           NaN   
1                  NaN             NaN                 NaN           NaN   
2                  NaN             NaN                 NaN           NaN   
3                  NaN             NaN                 NaN           NaN   
4                  NaN             NaN                 NaN           NaN   

   Unnamed: 20  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  

[5 rows x 21 columns]

In [1532]:
df.shape

(3665, 21)

Le fichier contient fichier 3665 lignes et 21 colonnes.

In [1533]:
mean_null_by_columns_df = df.isnull().mean()
mean_null_by_columns_df

Series Code                            0.000000
Topic                                  0.000000
Indicator Name                         0.000000
Short definition                       0.411733
Long definition                        0.000000
Unit of measure                        1.000000
Periodicity                            0.972988
Base Period                            0.914325
Other notes                            0.849386
Aggregation method                     0.987176
Limitations and exceptions             0.996180
Notes from original source             1.000000
General comments                       0.996180
Source                                 0.000000
Statistical concept and methodology    0.993724
Development relevance                  0.999181
Related source links                   0.941337
Other web links                        1.000000
Related indicators                     1.000000
License Type                           1.000000
Unnamed: 20                            1

In [1534]:
columns_with_no_null = mean_null_by_columns_df[mean_null_by_columns_df == 0.0]
columns_with_no_null

Series Code        0.0
Topic              0.0
Indicator Name     0.0
Long definition    0.0
Source             0.0
dtype: float64

Aucune données n'est manquante dans les colonnes ci-dessus

In [1535]:
columns_with_only_null = mean_null_by_columns_df[mean_null_by_columns_df == 1.0]
columns_with_only_null

Unit of measure               1.0
Notes from original source    1.0
Other web links               1.0
Related indicators            1.0
License Type                  1.0
Unnamed: 20                   1.0
dtype: float64

Les colonnes ci-dessus sont vides

In [1536]:
series = df

## Partie 2 : Sélectionnez les données pertinentes

Voici les colonnes que je pense qui vont m'être utile pour analyser le marché 

In [1537]:
dimensions = [
    "Enrolment in secondary education, both sexes (number)",
    "Enrolment in tertiary education per 100,000 inhabitants, both sexes",
    "Enrolment in tertiary education, all programmes, both sexes (number)",
    "Enrolment in upper secondary education, both sexes (number)",
    "Gross enrolment ratio, secondary, both sexes (%)",
    "Gross enrolment ratio, tertiary, both sexes (%)",
    "Gross enrolment ratio, upper secondary, both sexes (%)",
    "Net enrolment rate, secondary, both sexes (%)",
    "Net enrolment rate, upper secondary, both sexes (%)",
    "Barro-Lee: Average years of secondary schooling, age 15+, total",
    "Barro-Lee: Average years of tertiary schooling, age 20-24, female",
    "Barro-Lee: Percentage of population age 15+ with secondary schooling. Completed Secondary",
    "Barro-Lee: Percentage of population age 15-19 with tertiary schooling. Completed Tertiary",
    "Barro-Lee: Percentage of population age 25+ with tertiary schooling. Total (Incomplete and Completed Tertiary)",
    "Barro-Lee: Population in thousands, age 15+, total",
    "Capital expenditure as % of total expenditure in secondary public institutions (%)",
    "Capital expenditure as % of total expenditure in tertiary public institutions (%)",
    "DHS: Average years of schooling by age group. Age 15-19",
    "DHS: Gross attendance rate. Post Secondary",
    "DHS: Net attendance rate. Secondary",
    "DHS: Secondary completion rate",
    "Expenditure on education as % of total government expenditure (%)",
    "Expenditure on secondary as % of government expenditure on education (%)",
    "Expenditure on tertiary as % of government expenditure on education (%)",
    "Government expenditure in secondary institutions education as % of GDP (%)",
    "Government expenditure in tertiary institutions as % of GDP (%)",
    "Government expenditure on secondary education as % of GDP (%)",
    "Government expenditure on tertiary education as % of GDP (%)",
    "Internet users (per 100 people)",
    "MICS: Secondary completion rate",
    "Net enrolment rate, secondary, both sexes (%)",
    "Net enrolment rate, upper secondary, both sexes (%)",
    "Population growth (annual %)",
    "Population, ages 15-24, total",
    "Teachers in secondary education, both sexes (number)",
    "Teachers in tertiary education programmes, both sexes (number)",
]



In [1538]:
# Filter indicators column
filtered_data = stats[stats['Indicator Name'].isin(dimensions)]

In [1539]:
# Filter year columns[
filtered_data = filtered_data[['Country Name', 'Indicator Name', '2012', '2013', '2014', '2015', '2016']]
filtered_data

Country Name                                     Indicator Name  \
180      Arab World  Barro-Lee: Average years of secondary schoolin...   
213      Arab World  Barro-Lee: Average years of tertiary schooling...   
377      Arab World  Barro-Lee: Percentage of population age 15+ wi...   
386      Arab World  Barro-Lee: Percentage of population age 15-19 ...   
401      Arab World  Barro-Lee: Percentage of population age 25+ wi...   
...             ...                                                ...   
884923     Zimbabwe  Net enrolment rate, upper secondary, both sexe...   
885572     Zimbabwe                       Population growth (annual %)   
885747     Zimbabwe                      Population, ages 15-24, total   
886235     Zimbabwe  Teachers in secondary education, both sexes (n...   
886243     Zimbabwe  Teachers in tertiary education programmes, bot...   

                2012          2013          2014          2015     2016  
180              NaN           NaN           NaN           NaN      NaN  
213              NaN           NaN           NaN           NaN      NaN  
377              NaN           NaN           NaN           NaN      NaN  
386              NaN           NaN           NaN           NaN      NaN  
401              NaN           NaN           NaN           NaN      NaN  
...              ...           ...           ...           ...      ...  
884923           NaN  3.207115e+01           NaN           NaN      NaN  
885572  2.228306e+00  2.309366e+00  2.344799e+00  2.345643e+00  2.33607  
885747  3.383141e+06  3.371070e+06  3.354236e+06  3.333716e+06      NaN  
886235  4.175900e+04  4.258500e+04           NaN           NaN      NaN  
886243           NaN  5.537000e+03           NaN  7.561000e+03      NaN  

[8228 rows x 7 columns]

In [1540]:
filtered_data.isnull().mean()

Country Name      0.000000
Indicator Name    0.000000
2012              0.627491
2013              0.638430
2014              0.682547
2015              0.796062
2016              0.936558
dtype: float64

In [1541]:
countries_to_pop = ['Arab World', 'East Asia & Pacific',
       'East Asia & Pacific (excluding high income)', 'Euro area',
       'Europe & Central Asia',
       'Europe & Central Asia (excluding high income)', 'European Union',
       'Heavily indebted poor countries (HIPC)', 'High income',
       'Latin America & Caribbean',
       'Latin America & Caribbean (excluding high income)',
       'Least developed countries: UN classification',
       'Low & middle income', 'Low income', 'Lower middle income',
       'Middle East & North Africa',
       'Middle East & North Africa (excluding high income)',
       'Middle income', 'North America', 'OECD members', 'South Asia',
       'Sub-Saharan Africa', 'Sub-Saharan Africa (excluding high income)',
       'Upper middle income', 'World']

In [1542]:
filtered_data =  filtered_data[~filtered_data["Country Name"].isin(countries_to_pop)]

Filtre pour ne garder que les pays et pas les régions

In [1543]:
filtered_data

Country Name                                     Indicator Name  \
91805   Afghanistan  Barro-Lee: Average years of secondary schoolin...   
91838   Afghanistan  Barro-Lee: Average years of tertiary schooling...   
92002   Afghanistan  Barro-Lee: Percentage of population age 15+ wi...   
92011   Afghanistan  Barro-Lee: Percentage of population age 15-19 ...   
92026   Afghanistan  Barro-Lee: Percentage of population age 25+ wi...   
...             ...                                                ...   
884923     Zimbabwe  Net enrolment rate, upper secondary, both sexe...   
885572     Zimbabwe                       Population growth (annual %)   
885747     Zimbabwe                      Population, ages 15-24, total   
886235     Zimbabwe  Teachers in secondary education, both sexes (n...   
886243     Zimbabwe  Teachers in tertiary education programmes, bot...   

                2012          2013          2014          2015     2016  
91805            NaN           NaN           NaN           NaN      NaN  
91838            NaN           NaN           NaN           NaN      NaN  
92002            NaN           NaN           NaN           NaN      NaN  
92011            NaN           NaN           NaN           NaN      NaN  
92026            NaN           NaN           NaN           NaN      NaN  
...              ...           ...           ...           ...      ...  
884923           NaN  3.207115e+01           NaN           NaN      NaN  
885572  2.228306e+00  2.309366e+00  2.344799e+00  2.345643e+00  2.33607  
885747  3.383141e+06  3.371070e+06  3.354236e+06  3.333716e+06      NaN  
886235  4.175900e+04  4.258500e+04           NaN           NaN      NaN  
886243           NaN  5.537000e+03           NaN  7.561000e+03      NaN  

[7378 rows x 7 columns]

In [1544]:
df_melted = pd.melt(filtered_data, id_vars=['Country Name', 'Indicator Name'], var_name='year', value_name='value')
df_melted = df_melted.sort_values(by=['Country Name', 'Indicator Name', 'year']).reset_index(drop=True)
df_melted

Country Name                                     Indicator Name  year  \
0      Afghanistan  Barro-Lee: Average years of secondary schoolin...  2012   
1      Afghanistan  Barro-Lee: Average years of secondary schoolin...  2013   
2      Afghanistan  Barro-Lee: Average years of secondary schoolin...  2014   
3      Afghanistan  Barro-Lee: Average years of secondary schoolin...  2015   
4      Afghanistan  Barro-Lee: Average years of secondary schoolin...  2016   
...            ...                                                ...   ...   
36885     Zimbabwe  Teachers in tertiary education programmes, bot...  2012   
36886     Zimbabwe  Teachers in tertiary education programmes, bot...  2013   
36887     Zimbabwe  Teachers in tertiary education programmes, bot...  2014   
36888     Zimbabwe  Teachers in tertiary education programmes, bot...  2015   
36889     Zimbabwe  Teachers in tertiary education programmes, bot...  2016   

        value  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
4         NaN  
...       ...  
36885     NaN  
36886  5537.0  
36887     NaN  
36888  7561.0  
36889     NaN  

[36890 rows x 4 columns]

In [1545]:
df_pivoted = df_melted.pivot_table(index=['Country Name', 'year'], columns='Indicator Name', values='value', aggfunc='sum').reset_index()
# Renaming columns for clarity
df_pivoted.columns.name = None
df_pivoted


Country Name  year  \
0     Afghanistan  2012   
1     Afghanistan  2013   
2     Afghanistan  2014   
3     Afghanistan  2015   
4     Afghanistan  2016   
...           ...   ...   
1080     Zimbabwe  2012   
1081     Zimbabwe  2013   
1082     Zimbabwe  2014   
1083     Zimbabwe  2015   
1084     Zimbabwe  2016   

      Barro-Lee: Average years of secondary schooling, age 15+, total  \
0                                                   0.0                 
1                                                   0.0                 
2                                                   0.0                 
3                                                   0.0                 
4                                                   0.0                 
...                                                 ...                 
1080                                                0.0                 
1081                                                0.0                 
1082                                                0.0                 
1083                                                0.0                 
1084                                                0.0                 

      Barro-Lee: Average years of tertiary schooling, age 20-24, female  \
0                                                   0.0                   
1                                                   0.0                   
2                                                   0.0                   
3                                                   0.0                   
4                                                   0.0                   
...                                                 ...                   
1080                                                0.0                   
1081                                                0.0                   
1082                                                0.0                   
1083                                                0.0                   
1084                                                0.0                   

      Barro-Lee: Percentage of population age 15+ with secondary schooling. Completed Secondary  \
0                                                   0.0                                           
1                                                   0.0                                           
2                                                   0.0                                           
3                                                   0.0                                           
4                                                   0.0                                           
...                                                 ...                                           
1080                                                0.0                                           
1081                                                0.0                                           
1082                                                0.0                                           
1083                                                0.0                                           
1084                                                0.0                                           

      Barro-Lee: Percentage of population age 15-19 with tertiary schooling. Completed Tertiary  \
0                                                   0.0                                           
1                                                   0.0                                           
2                                                   0.0                                           
3                                                   0.0                                           
4                                                   0.0                                           
...                                                 ...                                           
1080                

In [1546]:
df_pivoted

Country Name  year  \
0     Afghanistan  2012   
1     Afghanistan  2013   
2     Afghanistan  2014   
3     Afghanistan  2015   
4     Afghanistan  2016   
...           ...   ...   
1080     Zimbabwe  2012   
1081     Zimbabwe  2013   
1082     Zimbabwe  2014   
1083     Zimbabwe  2015   
1084     Zimbabwe  2016   

      Barro-Lee: Average years of secondary schooling, age 15+, total  \
0                                                   0.0                 
1                                                   0.0                 
2                                                   0.0                 
3                                                   0.0                 
4                                                   0.0                 
...                                                 ...                 
1080                                                0.0                 
1081                                                0.0                 
1082                                                0.0                 
1083                                                0.0                 
1084                                                0.0                 

      Barro-Lee: Average years of tertiary schooling, age 20-24, female  \
0                                                   0.0                   
1                                                   0.0                   
2                                                   0.0                   
3                                                   0.0                   
4                                                   0.0                   
...                                                 ...                   
1080                                                0.0                   
1081                                                0.0                   
1082                                                0.0                   
1083                                                0.0                   
1084                                                0.0                   

      Barro-Lee: Percentage of population age 15+ with secondary schooling. Completed Secondary  \
0                                                   0.0                                           
1                                                   0.0                                           
2                                                   0.0                                           
3                                                   0.0                                           
4                                                   0.0                                           
...                                                 ...                                           
1080                                                0.0                                           
1081                                                0.0                                           
1082                                                0.0                                           
1083                                                0.0                                           
1084                                                0.0                                           

      Barro-Lee: Percentage of population age 15-19 with tertiary schooling. Completed Tertiary  \
0                                                   0.0                                           
1                                                   0.0                                           
2                                                   0.0                                           
3                                                   0.0                                           
4                                                   0.0                                           
...                                                 ...                                           
1080                

In [1553]:
years = df_pivoted.year.unique().tolist()

for year in years:
    lign_equal_to_zero_percentage_mean = 0
    df = df_pivoted[df_pivoted['year'] == year]
    for dimension in dimensions:
        print(f"{round((df[dimension] == 0).mean(),2)} : {year} {dimension}")
        lign_equal_to_zero_percentage_mean += round((df[dimension] == 0).mean(),2)
    print(lign_equal_to_zero_percentage_mean / (len(dimensions)))
    print('----------------------------')

0.31 : 2012 Enrolment in secondary education, both sexes (number)
0.39 : 2012 Enrolment in tertiary education per 100,000 inhabitants, both sexes
0.35 : 2012 Enrolment in tertiary education, all programmes, both sexes (number)
0.3 : 2012 Enrolment in upper secondary education, both sexes (number)
0.34 : 2012 Gross enrolment ratio, secondary, both sexes (%)
0.37 : 2012 Gross enrolment ratio, tertiary, both sexes (%)
0.33 : 2012 Gross enrolment ratio, upper secondary, both sexes (%)
0.55 : 2012 Net enrolment rate, secondary, both sexes (%)
0.76 : 2012 Net enrolment rate, upper secondary, both sexes (%)
1.0 : 2012 Barro-Lee: Average years of secondary schooling, age 15+, total
1.0 : 2012 Barro-Lee: Average years of tertiary schooling, age 20-24, female
1.0 : 2012 Barro-Lee: Percentage of population age 15+ with secondary schooling. Completed Secondary
1.0 : 2012 Barro-Lee: Percentage of population age 15-19 with tertiary schooling. Completed Tertiary
1.0 : 2012 Barro-Lee: Percentage of po